apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'Prometheus'
        static_configs:
          - targets: ['localhost:9090']
        labels:
          group: 'DevTown-EC2'

      - job_name: 'DevTown-ec2-LMS'
        static_configs:
          - targets: ['13.126.69.74:9100']
        labels:
          group: 'DevTown-EC2'

      - job_name: 'DevTown-ec2-KOSH'
        static_configs:
          - targets: ['3.111.23.70:9100']
        labels:
          group: 'DevTown-EC2'

      - job_name: 'DevTown-ec2-Cluster-Node1'
        static_configs:
          - targets: ['3.93.46.247:9100']
        labels:
          group: 'DevTown-EC2'

      - job_name: 'DevTown-ec2-Sales'
        static_configs:
          - targets: ['13.233.225.162:9100']
        labels:
          group: 'DevTown-EC2'

      - job_name: 'DevTown-ec2-CertificatePortal'
        static_configs:
          - targets: ['3.7.158.33:9100']
        labels:
          group: 'DevTown-EC2'

      - job_name: 'DevTown-CloudWatch'
        static_configs:
          - targets: ['3.93.46.247:32106']

      - job_name: 'DevTown-LMS-Auth-Service'
        metrics_path: '/metrics' 
        static_configs:
          - targets: ['13.126.69.74:8080']

      - job_name: 'DevTown-LMS-Student-Service'
        metrics_path: '/metrics' 
        static_configs:
          - targets: ['13.126.69.74:8083']    

      - job_name: 'DevTown-LMS-Admin-Service'
        metrics_path: '/metrics' 
        static_configs:
          - targets: ['13.126.69.74:3000']

      - job_name: 'TORUS-ec2-GSC'
        static_configs:
          - targets: ['13.203.38.108:9100']
        labels:
          group: 'Torus-EC2'          

