apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring  # You can change the namespace if needed
spec:
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30081
  selector:
    app: prometheus
  type: NodePort