apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
      annotations:
        checksum/prometheus-config: "3cdc3e47b56d6e59f75f7cd51d3b42f59879ccabb321a6a80fbacb7b076c7f1f"  
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.35.0
          ports:
            - containerPort: 9090
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
