apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: monitoring  # You can change the namespace if needed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi